import { createApp } from 'vue'
// import App from './01-组件内的嵌套使用/App.vue'
// import App from './02-组件通信-父传子/App.vue'
// import App from './03-组件通信-子传父/App.vue'
// import App from './04-组件通信案例练习/App.vue'
// import App from './05-组件通信-插槽/App.vue'
// import App from './06-组件插槽-具名插槽/App.vue'
import App from './07-组件插槽-作用域插槽/App.vue'
// import App from './08-Provide和inject/App.vue'
// import App from './09-事件总线的使用/App.vue'
// import App from './10-生命周期函数的使用/App.vue'
// import App from './11-ref获取元素组件/App.vue'
// import App from './12-动态组件的使用/App.vue'
// import App from './13-keep-alive的使用/App.vue'
// import App from './13-keep-alive的使用/App.vue'
// import App from './15-组件的v-model的使用/App.vue'
// import App from './16-组件的混入Mixin/App.vue'


createApp(App).mount('#app')
